### ISSUE TITLE
Images no longer display

### ISSUE THREAD

**Issue by kenroyandfamily** [alexa/alexa-presentation-language-apl-button-and-voice-interactivty-demo#3]
I've been using this project as an example to convert my project to use the new Alex APL, but for some reason my device nor the Alexa Developer Console display many images such as the ones in this project.  I can get some images to display but not all my images and I haven't a clue why, but I don't think it is the project.  Has anyone else experienced this?

**Comment by aszk** [comment]
Could you contact us https://alexa.design/contactus with more details?
